### ISSUE TITLE
Installation of capped_mixed

### ISSUE THREAD

**Issue by zhengp0** [bradbell/dismod_at#1]
Hi!

Please induce the environment variable PKG_CONFIG_PATH from bin/run_cmake.sh to bin/install_cppad_mixed.sh to avoid the need to define the variable manually between the installations.

Thanks very much!!
Best,
Peng

**Comment by bradbell** [comment]
I just noticed this issue is still open. Looking at the code in bin/install_cppad_mixed.sh it seems that PKG_CONFIG_PATH is being set the same as for bin/run_cmake.sh. Is this still a problem ?

**Comment by zhengp0** [comment]
Thanks very much! It is good now.
Fixed in commit `07b5b2e15cff58c2d7996f18675b31aecf549098`.
