### ISSUE TITLE
Convergence problem in the inner problem starting at a particular prior value

### ISSUE THREAD

**Issue by gma-uw** [bradbell/dismod_at#2]
This test sets the iota_prior = iota_true * scalar. If the scalar is 100, 1.999, or 2.001 the problem converges. But if the scalar is 2.0, dismod_at exhibits the following behavior:
iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
   0  2.5954423e+02 1.39e-02 1.00e+00  -1.0 0.00e+00    -  0.00e+00 0.00e+00   0
   1  2.5954031e+02 9.76e-03 6.70e-01  -1.7 1.39e-02    -  9.96e-01 1.00e+00h  1
   2  2.5953723e+02 1.81e-03 7.49e-01  -1.7 3.00e-03    -  1.00e+00 1.00e+00h  1
   3  2.5953715e+02 7.75e-05 3.32e-02  -1.7 8.28e-04    -  1.00e+00 1.00e+00h  1
dismod_at warning: cppad_mixed: optimize_random: Maximum_Iterations_Exceeded
   4  2.5953715e+02 3.88e-05 8.31e-01  -2.5 3.86e-05    -  1.00e+00 5.00e-01h  2
dismod_at warning: cppad_mixed: optimize_random: Maximum_Iterations_Exceeded

and so on, and the problem doesn't converge.

[test_fit_child_fails_at_2.py.zip](https://github.com/bradbell/dismod_at/files/4610801/test_fit_child_fails_at_2.py.zip)

**Comment by bradbell** [comment]
- Here is the error message I get when I execute test_fit_child_fails_at_2.py with the current dismod_at:
- i test_fit_child_fails_at_2.py 
junk>python test_fit_child_fails_at_2.py 
/home/bradbell/trash/junk/test_fit_child_fails_at_2.py:19: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  import distutils.dir_util
dismod_at example.db init
Traceback (most recent call last):
  File "/home/bradbell/trash/junk/test_fit_child_fails_at_2.py", line 215, in <module>
    dismod_at.system_command_prc([ program, file_name, 'init' ])
  File "/home/bradbell/prefix/dismod_at/lib/python3.10/site-packages/dismod_at/system_command_prc.py", line 188, in system_command_prc
    assert False, msg
AssertionError: system_command_prc failed: returncode = 1
dismod_at error: This group name is also a subgroup name in a different row of the subgroup table
detected in subgroup table in row with subgroup_id = 1

**Comment by gma-uw** [comment]
bash-3.2$ pwd
/Users/gma/Projects/IHME/GIT/dismod_at.git/build
bash-3.2$ make check
[ 54%] Built target devel
[ 55%] Built target dismod_at
sed: -I or -i may not be used with stdin
make[3]: *** [test/user/CMakeFiles/check_test_user_zero_random_2] Error 1
make[2]: *** [test/user/CMakeFiles/check_test_user_zero_random_2.dir/all] Error 2
make[1]: *** [CMakeFiles/check.dir/rule] Error 2
make: *** [check] Error 2

I can't find the source of this build error.

**Comment by gma-uw** [comment]
Obsolete
