### ISSUE TITLE
trace-adaptive derivative errors in a node, group, and covariate simulation

### ISSUE THREAD

**Issue by gma-uw** [bradbell/dismod_at#3]
The attached file creates a simulated data set with covariate, node, and group effects. The trace-adaptive derivative checker is detecting the following problems.

dismod_at example.db fit both
<pre>
   j       step          f       grad        apx        err
   0  9.999e-11      -62.5 -1.478e-12          0          1
   1      0.001      -62.5 -3.552e-08 -3.561e-08   0.001249

   i   j       step          f       grad        apx        err
   0   0  3.556e-05  5.135e-16  5.025e-14  3.512e-12     0.9718
   1   0  1.125e-08     0.2715     -229.1     -229.1  1.556e-11
   0   1  3.557e-05  5.135e-16 -2.219e-15 -4.292e-12      0.999
   1   1      0.002     0.2715         -1         -1  9.992e-16

  j1  j2       step       hess        apx        err
   0   0      2e-10  5.248e+04  5.248e+04  3.334e-07
   1   0      2e-10  1.496e-13  0.0004302  8.198e-09
   1   1  1.125e-08        595        593   0.001122
</pre>
dismod_at warning: cppad_mixed: optimize_fixed: adaptive derivative test failed
dismod_at error: cppad_mixed: optimize_fixed: Solve_Succeeded
command failed: flag = 1

derivative_errors.py.zip
[derivative_errors.py.zip](https://github.com/bradbell/dismod_at/files/4669681/derivative_errors.py.zip)

**Comment by bradbell** [comment]
Looking at the end of file derivative_errors.zip ser see
<pre>
#
program = 'dismod_at'
dismod_at.system_command_prc([ program, file_name, 'init' ])
dismod_at.system_command_prc([ program, file_name, 'fit', 'fixed'])
#
# Fit both fixed and random effects
dismod_at.system_command_prc([ program, file_name, 'set', 'start_var', 'fit_var'])
dismod_at.system_command_prc([ program, file_name, 'set', 'scale_var', 'fit_var'])
dismod_at.system_command_prc(['dismodat.py', file_name, 'db2csv'])

dismod_at.system_command_prc([ program, file_name, 'fit', 'both'])
</pre>
Note that the first fit fails, so the stuff after that is garbage (there was not fit to replace the start and scale tables with). Lets look at the first derivative trace:
<pre>
   j       step          f       grad        apx        err
   0  0.0009999       9856  4.875e+05  4.875e+05   5.97e-17
   1      0.001       9856       9503       9503  4.011e-07

  j1  j2       step       hess        apx        err
   0   0      0.002  2.408e+07  2.408e+07  8.767e-16
   1   0      0.002  8.633e+05  8.633e+05  1.263e-16
   1   1      0.002  4.316e+04  4.316e+04  2.421e-07

</pre>
which is all good. (Note that I have done some improvement to the cppad_mixed adaptive derivative test and I will update dismod_at to use it.)

**Comment by gma-uw** [comment]
What do you mean the first fit fails? I see this:

dismod_at example.db init
dismod_at example.db fit fixed

   j       step          f       grad        apx        err
   0  9.999e-11       9856  4.875e+05  4.875e+05  1.194e-08
   1      1e-10       9856       9503       9503    5.7e-07

  j1  j2       step       hess        apx        err
   0   0      2e-10  2.408e+07  2.408e+07  4.603e-09
   1   0      2e-10  8.633e+05  8.633e+05  5.304e-10
   1   1      2e-10  4.316e+04  4.316e+04  6.284e-08
This is Ipopt version 3.12.6, running with linear solver mumps.
NOTE: Other linear solvers might be more efficient (see Ipopt documentation).

Number of nonzeros in equality constraint Jacobian...:        0
Number of nonzeros in inequality constraint Jacobian.:        0
Number of nonzeros in Lagrangian Hessian.............:        3

Total number of variables............................:        2
                     variables with only lower bounds:        0
                variables with lower and upper bounds:        1
                     variables with only upper bounds:        0
Total number of equality constraints.................:        0
Total number of inequality constraints...............:        0
        inequality constraints with only lower bounds:        0
   inequality constraints with lower and upper bounds:        0
        inequality constraints with only upper bounds:        0

iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
   0  2.0216748e-02 0.00e+00 1.00e+00  -1.0 0.00e+00    -  0.00e+00 0.00e+00   0
   1  1.0234888e-02 0.00e+00 9.42e-02  -1.7 2.76e-01    -  1.00e+00 1.00e+00f  1
   2  2.1404457e-03 0.00e+00 2.70e-03  -2.5 1.73e-02    -  1.00e+00 1.00e+00f  1
   3  2.9519579e-04 0.00e+00 7.26e-03  -3.8 7.43e-02    -  1.00e+00 1.00e+00f  1
   4  6.0580019e-06 0.00e+00 4.99e-03  -3.8 1.27e-01    -  1.00e+00 1.00e+00f  1
   5 -2.9886968e-05 0.00e+00 7.14e-04  -3.8 1.22e-01    -  1.00e+00 1.00e+00f  1
   6 -4.0984611e-05 0.00e+00 7.01e-04  -5.7 1.16e-01    -  1.00e+00 1.00e+00f  1
   7 -4.1179948e-05 0.00e+00 4.33e-06  -5.7 2.17e-02    -  1.00e+00 1.00e+00f  1
   8 -4.1182140e-05 0.00e+00 2.33e-07  -8.6 2.02e-03    -  1.00e+00 1.00e+00f  1
   9 -4.1182140e-05 0.00e+00 7.08e-13  -8.6 5.79e-06    -  1.00e+00 1.00e+00f  1
iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
  10 -4.1182140e-05 0.00e+00 3.21e-13 -12.9 2.23e-06    -  1.00e+00 1.00e+00f  1

Number of Iterations....: 10

                                   (scaled)                 (unscaled)
Objective...............:  -4.1182140078656844e-05   -4.1182140078656844e-05
Dual infeasibility......:   3.2088955999711748e-13    3.2088955999711748e-13
Constraint violation....:   0.0000000000000000e+00    0.0000000000000000e+00
Complementarity.........:   1.3109496873569543e-13    1.3109496873569543e-13
Overall NLP error.......:   3.2088955999711748e-13    3.2088955999711748e-13


Number of objective function evaluations             = 11
Number of objective gradient evaluations             = 11
Number of equality constraint evaluations            = 0
Number of inequality constraint evaluations          = 0
Number of equality constraint Jacobian evaluations   = 0
Number of inequality constraint Jacobian evaluations = 0
Number of Lagrangian Hessian evaluations             = 10
Total CPU secs in IPOPT (w/o function evaluations)   =      0.005
Total CPU secs in NLP function evaluations           =      0.000

EXIT: Optimal Solution Found.




On May 27, 2020, at 2:29 PM, Brad Bell <notifications@github.com<mailto:notifications@github.com>> wrote:



Looking at the end of file derivative_errors.zip ser see

#
program = 'dismod_at'
dismod_at.system_command_prc([ program, file_name, 'init' ])
dismod_at.system_command_prc([ program, file_name, 'fit', 'fixed'])
#
# Fit both fixed and random effects
dismod_at.system_command_prc([ program, file_name, 'set', 'start_var', 'fit_var'])
dismod_at.system_command_prc([ program, file_name, 'set', 'scale_var', 'fit_var'])
dismod_at.system_command_prc(['dismodat.py', file_name, 'db2csv'])

dismod_at.system_command_prc([ program, file_name, 'fit', 'both'])


Note that the first fit fails, so the stuff after that is garbage (there was not fit to replace the start and scale tables with). Lets look at the first derivative trace:

   j       step          f       grad        apx        err
   0  0.0009999       9856  4.875e+05  4.875e+05   5.97e-17
   1      0.001       9856       9503       9503  4.011e-07

  j1  j2       step       hess        apx        err
   0   0      0.002  2.408e+07  2.408e+07  8.767e-16
   1   0      0.002  8.633e+05  8.633e+05  1.263e-16
   1   1      0.002  4.316e+04  4.316e+04  2.421e-07



which is all good. (Note that I have done some improvement to the cppad_mixed adaptive derivative test and I will update dismod_at to use it.)

**Comment by bradbell** [comment]
I have linked in the improved version of the trace-adaptive output; see the heading 05-27 on
https://bradbell.github.io/dismod_at/doc/whats_new_2020.htm

Unless you have other questions about this case, please close this issue.

**Comment by bradbell** [comment]
<pre>
dismod_at example.db init
dismod_at example.db fit fixed
This is Ipopt version 3.12.6, running with linear solver mumps.
NOTE: Other linear solvers might be more efficient (see Ipopt documentation).

Number of nonzeros in equality constraint Jacobian...:        0
Number of nonzeros in inequality constraint Jacobian.:        0
Number of nonzeros in Lagrangian Hessian.............:        3

Total number of variables............................:        2
                     variables with only lower bounds:        0
                variables with lower and upper bounds:        1
                     variables with only upper bounds:        0
Total number of equality constraints.................:        0
Total number of inequality constraints...............:        0
        inequality constraints with only lower bounds:        0
   inequality constraints with lower and upper bounds:        0
        inequality constraints with only upper bounds:        0

iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
   0  2.0216748e-02 0.00e+00 1.00e+00  -1.0 0.00e+00    -  0.00e+00 0.00e+00   0
   1  1.0234888e-02 0.00e+00 9.42e-02  -1.7 2.76e-01    -  1.00e+00 1.00e+00f  1
   2  2.1404457e-03 0.00e+00 2.70e-03  -2.5 1.73e-02    -  1.00e+00 1.00e+00f  1
   3  2.9519579e-04 0.00e+00 7.26e-03  -3.8 7.43e-02    -  1.00e+00 1.00e+00f  1
   4  6.0580019e-06 0.00e+00 4.99e-03  -3.8 1.27e-01    -  1.00e+00 1.00e+00f  1
   5 -2.9886968e-05 0.00e+00 7.14e-04  -3.8 1.22e-01    -  1.00e+00 1.00e+00f  1
   6 -4.0984611e-05 0.00e+00 7.01e-04  -5.7 1.16e-01    -  1.00e+00 1.00e+00f  1
   7 -4.1179948e-05 0.00e+00 4.33e-06  -5.7 2.17e-02    -  1.00e+00 1.00e+00f  1
   8 -4.1182140e-05 0.00e+00 2.33e-07  -8.6 2.02e-03    -  1.00e+00 1.00e+00f  1
   9 -4.1182140e-05 0.00e+00 7.08e-13  -8.6 5.79e-06    -  1.00e+00 1.00e+00f  1
iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
  10 -4.1182140e-05 0.00e+00 3.21e-13 -12.9 2.23e-06    -  1.00e+00 1.00e+00f  1

Number of Iterations....: 10

                                   (scaled)                 (unscaled)
Objective...............:  -4.1182140078656844e-05   -4.1182140078656844e-05
Dual infeasibility......:   3.2090914803515040e-13    3.2090914803515040e-13
Constraint violation....:   0.0000000000000000e+00    0.0000000000000000e+00
Complementarity.........:   1.3109496873569543e-13    1.3109496873569543e-13
Overall NLP error.......:   3.2090914803515040e-13    3.2090914803515040e-13


Number of objective function evaluations             = 11
Number of objective gradient evaluations             = 11
Number of equality constraint evaluations            = 0
Number of inequality constraint evaluations          = 0
Number of equality constraint Jacobian evaluations   = 0
Number of inequality constraint Jacobian evaluations = 0
Number of Lagrangian Hessian evaluations             = 10
Total CPU secs in IPOPT (w/o function evaluations)   =      0.010
Total CPU secs in NLP function evaluations           =      0.001

EXIT: Optimal Solution Found.
dismod_at example.db set start_var fit_var
dismod_at example.db set scale_var fit_var
dismodat.py example.db db2csv
dismodat.py: OK
dismod_at example.db fit both

   j       step          f       grad        apx        err
   0  0.0009999      -62.5 -1.705e-12          0          1
   1      0.001      -62.5 -3.552e-08 -3.563e-08   0.001548

   i   j       step          f       grad        apx        err
   0   0      0.002  5.135e-16  5.025e-14 -4.164e-14          1
   0   1      0.002  5.135e-16 -2.219e-15          0          1

  j1  j2       step       hess        apx        err
   1   1  1.125e-08        595        593   0.001122
dismod_at warning: cppad_mixed: optimize_fixed: adaptive derivative test failed
dismod_at error: cppad_mixed: optimize_fixed: Solve_Succeeded
dismod_at: /home/bradbell/repo/dismod_at.git/devel/utility/error_exit.cpp:124: void dismod_at::error_exit(const string&, const string&, const size_t&): Assertion `false' failed.
command failed: flag = -6
</pre>

**Comment by gma-uw** [comment]
What do you mean the first fit fails? I see this:

dismod_at example.db init
dismod_at example.db fit fixed
<pre>
   j       step          f       grad        apx        err
   0  9.999e-11       9856  4.875e+05  4.875e+05  1.194e-08
   1      1e-10       9856       9503       9503    5.7e-07

  j1  j2       step       hess        apx        err
   0   0      2e-10  2.408e+07  2.408e+07  4.603e-09
   1   0      2e-10  8.633e+05  8.633e+05  5.304e-10
   1   1      2e-10  4.316e+04  4.316e+04  6.284e-08
This is Ipopt version 3.12.6, running with linear solver mumps.
NOTE: Other linear solvers might be more efficient (see Ipopt documentation).

Number of nonzeros in equality constraint Jacobian...:        0
Number of nonzeros in inequality constraint Jacobian.:        0
Number of nonzeros in Lagrangian Hessian.............:        3

Total number of variables............................:        2
                     variables with only lower bounds:        0
                variables with lower and upper bounds:        1
                     variables with only upper bounds:        0
Total number of equality constraints.................:        0
Total number of inequality constraints...............:        0
        inequality constraints with only lower bounds:        0
   inequality constraints with lower and upper bounds:        0
        inequality constraints with only upper bounds:        0

iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
   0  2.0216748e-02 0.00e+00 1.00e+00  -1.0 0.00e+00    -  0.00e+00 0.00e+00   0
   1  1.0234888e-02 0.00e+00 9.42e-02  -1.7 2.76e-01    -  1.00e+00 1.00e+00f  1
   2  2.1404457e-03 0.00e+00 2.70e-03  -2.5 1.73e-02    -  1.00e+00 1.00e+00f  1
   3  2.9519579e-04 0.00e+00 7.26e-03  -3.8 7.43e-02    -  1.00e+00 1.00e+00f  1
   4  6.0580019e-06 0.00e+00 4.99e-03  -3.8 1.27e-01    -  1.00e+00 1.00e+00f  1
   5 -2.9886968e-05 0.00e+00 7.14e-04  -3.8 1.22e-01    -  1.00e+00 1.00e+00f  1
   6 -4.0984611e-05 0.00e+00 7.01e-04  -5.7 1.16e-01    -  1.00e+00 1.00e+00f  1
   7 -4.1179948e-05 0.00e+00 4.33e-06  -5.7 2.17e-02    -  1.00e+00 1.00e+00f  1
   8 -4.1182140e-05 0.00e+00 2.33e-07  -8.6 2.02e-03    -  1.00e+00 1.00e+00f  1
   9 -4.1182140e-05 0.00e+00 7.08e-13  -8.6 5.79e-06    -  1.00e+00 1.00e+00f  1
iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
  10 -4.1182140e-05 0.00e+00 3.21e-13 -12.9 2.23e-06    -  1.00e+00 1.00e+00f  1

Number of Iterations....: 10

                                   (scaled)                 (unscaled)
Objective...............:  -4.1182140078656844e-05   -4.1182140078656844e-05
Dual infeasibility......:   3.2088955999711748e-13    3.2088955999711748e-13
Constraint violation....:   0.0000000000000000e+00    0.0000000000000000e+00
Complementarity.........:   1.3109496873569543e-13    1.3109496873569543e-13
Overall NLP error.......:   3.2088955999711748e-13    3.2088955999711748e-13


Number of objective function evaluations             = 11
Number of objective gradient evaluations             = 11
Number of equality constraint evaluations            = 0
Number of inequality constraint evaluations          = 0
Number of equality constraint Jacobian evaluations   = 0
Number of inequality constraint Jacobian evaluations = 0
Number of Lagrangian Hessian evaluations             = 10
Total CPU secs in IPOPT (w/o function evaluations)   =      0.005
Total CPU secs in NLP function evaluations           =      0.000

EXIT: Optimal Solution Found.

</pre>

**Comment by bradbell** [comment]
Here is why the derivative test on the constraint is failing. It turns out that the derivative of the constraint function with respect to the optimal fixed effects is zero. (As I recall. Peng Zheng has a proof of this for linear mixed effects models which this example is). Since the the true derivative value is zero, the relative error in the derivative is all noise.

I have added a subgroup example that does what I think you were trying to do in this example; see
https://bradbell.github.io/dismod_at/doc/user_subgroup_mulcov.py.htm
