### ISSUE TITLE
Location, group, and sex covariate fitting problem example.

### ISSUE THREAD

**Issue by gma-uw** [bradbell/dismod_at#4]
This example demonstrates problems fitting what seems to be a common situation: that being data from different locations that is grouped, and has a study covariate, in this case a sex covariate.

The example includes the following:

1) A parent location with 2 child random effects
2) A study covariate (sex) that applies across all data (between) groups.
    (Note that estimating a covariate across groups is not currently implemented by dismod)
3) A group covariate with 2 subgroup random effects
4) Optionally, a second group with no subgroups.

Supplying the second group (group none), in addition to the 2 nominal subgroups (s1, s2 in g1),
provides enough information to resolve all of the variables.

I think the second group gives insight into the rate and location effects, which
disambiguates the g1 group/subgroups and sex covariate fits.

If the second group is not included, the sum_random_zero constraints are unsuccessful, and
the solution is wrong. Predictions from the fit do not match the measured data.

[locations_groups_covariates.py.zip](https://github.com/bradbell/dismod_at/files/4773384/locations_groups_covariates.py.zip)

**Comment by bradbell** [comment]
Are you trying to have one group covariate apply to all the data and a different group covariate only apply to a subset of the data ?

**Comment by gma-uw** [comment]
I have about 8 different configurations of covariates and groups that fail, but you don't like complex examples so I just picked the one.

A likely situation, I think anyway, is:

A parent with child random effects.

A group with subgroup random effects.

A sex covariate that applies to all the data, regardless of the data group.


So right here, we have already have a problem. If the sex covariate must specify a group, then the sex and group covariates are ambiguous.

This particular setup has a second group without a sex covariate. It seems this second group gives us estimates for the rate and location effects, which makes everything else fall into place.

But, this may require some more thinking.

Does this answer your question?


On Jun 12, 2020, at 2:50 PM, Brad Bell <notifications@github.com<mailto:notifications@github.com>> wrote:



Are you trying to have one group covariate apply to all the data and a different group covariate only apply to a subset of the data ?

**Comment by bradbell** [comment]
My point is that you cannot have a covariate that spans multiple groups, as you seem to be trying to do from your description. That would be a new feature request.
